version: '3.1'
services:
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"
    volumes:
    - postgres_container:/var/lib/postgres

volumes:
  postgres_container:
